db-uri = "postgres://authenticator:authenticator@127.0.0.1:54329/finance"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "local-dev-jwt-secret-please-do-not-use-in-production-0123456789"
server-host = "127.0.0.1"
server-port = 3001
db-pool = 5
log-level = "warn"
